[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://kmxjx8sunf.execute-api.us-east-1.amazonaws.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
